#error (1:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got '﻿Feature: CreateSelfServiceViaApi'
#error (2:2): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Self Service'
#error (4:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Background: Pre-Conditions'
#error (5:2): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Given User is logged in to the Evergreen via API'
#error (8:1): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Scenario: EvergreenJnr_AdminPage_CheckThatUserIsAbleToCreateAndGetSelfServiceViaApi'
#error (9:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'When User creates Self Service via API'
#error (10:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got '| ServiceId | Name                      | ServiceIdentifier | Enabled | ObjectType | ObjectTypeId | StartDate              | EndDate                | SelfServiceURL | AllowAnonymousUsers | ScopeId |'
#error (11:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got '| 1         | TestSelfService_name11_v1 | id191811          | false   | Devimdmdmm | 3            | 2019-12-10T21:34:47.24 | 2019-12-31T21:34:47.24 | URL            | true                | 2       |'
#error (12:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Then User checks the created Self Service via API'
#error (13:0): unexpected end of file, expected: #TagLine, #FeatureLine, #Comment, #Empty
