#error (1:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got '﻿Feature: CreateSelfService'
#error (2:2): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Self Service'
#error (4:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Background: Pre-Conditions'
#error (5:2): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Given User is logged in to the Evergreen'
#error (6:2): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Then Evergreen Dashboards page should be displayed to the user'
#error (9:1): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Scenario: EvergreenJnr_AdminPage_CheckThatUserIsAbleToCreateSelfService'
#error (10:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'When User clicks 'Admin' on the left-hand menu'
#error (11:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'When User navigates to the 'Self Service' left menu item'
#error (12:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Then Page with 'Create Self Service' header is displayed to user'
#error (13:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'When User clicks 'CREATE SELF SERVICE' button'
#error (14:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Then Page with 'Create Self Service' header is displayed to user'
